config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :hotels do
    resources :rooms    
  end
  
  resources :rooms  
  
  root 'welcome#index'  
  

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :rooms
  validates :hotelname, :presence => true
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
  validates_associated :hotel
end

app/models/user.rb
class User < ActiveRecord::Base     
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.order("hotelname").all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:hotelname, :address, :website, :phone)
    end
end

app/controllers/roomcon_old.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
   end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def currency
      
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomnumber, :roomtype, :roomdescription, :roomprice ,:hotelname)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  
  def index
    @rooms = Room.order("hotelname").all
  end
  
  def show
  end
  
  def new
    @hotel = Hotel.find_by_id(params[:hotel_id])
    @room = @hotel.rooms.build
    @room = Room.new
  end
  
  def edit
    
  end

  def create
    
    @room = Room.create(room_params)
    @room.hotel = @current_hotel
        
    if @room.save
      flash[:notice] = "Room was successfully saved"
      redirect_to hotels_path
    else
      flash[:notice] = "There was an error"
    end
  end
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:roomnumber, :roomtype, :roomdescription, :roomprice, :hotelname, :hotel_id)
  end  

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hotels/_form.html.haml
= form_for(@hotel) do |f|
  - if @hotel.errors.any?
    #error_explanation
      %h2
        = pluralize(@hotel.errors.count, "error")
        prohibited this hotel from being saved:
      %ul
        - @hotel.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :hotelname, 'Hotel Name'
    %br/
    = f.text_field :hotelname
  .field
    = f.label :address, 'Address'
    %br/
    = f.text_area :address
  .field
    = f.label :website, 'Website'
    %br/
    = f.text_area :website
  .field
    = f.label :phone, 'Phone Number'
    %br/
    = f.text_area :phone
  .actions
    = f.submit

app/views/hotels/edit.html.haml
%banner2
  Hotel Listing

= render 'form'

= link_to 'Show', @hotel
|
= link_to 'Back', hotels_path
|
= link_to 'Home Page', root_path

app/views/hotels/index.html.haml
%banner2
  Listing of Hotels
%p#notice= notice
%table.table.table-bordered.table-striped.table-hover
  %thead
    %tr
      %th Number
      %th Hotel Name
      %th Address
      %th Website
      %th Phone
      %th Select Option
  %tbody
    - @hotels.each_with_index do |hotel, index|
      %tr
        %td= (index+1)
        %td= hotel.hotelname
        %td= hotel.address
        %td= hotel.website
        %td= hotel.phone
        %td
          .dropdown
            %a#dLabel{"aria-expanded" => "false", "aria-haspopup" => "true", "data-target" => "#", "data-toggle" => "dropdown", :href => "http://example.com"}
              Action
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dLabel", :role => "menu"}
              %li= link_to 'Show', hotel
              %li= link_to 'Edit', edit_hotel_path(hotel)
              %li= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' }
              %li= link_to 'Add Room', new_hotel_room_path(hotel)
%br/
= link_to 'New Hotel', new_hotel_path
|
= link_to 'Home Page', root_path

app/views/hotels/new.html.haml
%banner2
  Add A New Hotel

= render 'form'

= link_to 'Back', hotels_path
|
= link_to 'Home Page', root_path

app/views/hotels/show.html.haml
%banner2
  Information about the #{@hotel.hotelname}  
%p#notice= notice
%p
  %strong Hotel Name:
  = @hotel.hotelname
%p
  %strong Address:
  = @hotel.address
%p
  %strong Website:
  = @hotel.website
%p
  %strong Phone:
  = @hotel.phone
= link_to 'Edit', edit_hotel_path(@hotel)
|
= link_to 'Back', hotels_path
|
= link_to 'Home Page', root_path
|
= link_to 'Add Room', new_hotel_room_path(@hotel)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Project
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => root_path} Group 6 Project
          - if user_signed_in?
            %a.navbar-brand ||
            %a.navbar-brand{:href => destroy_user_session_path, "data-method" => :delete} Welcome #{current_user.email}  Not you?
        #navbar.navbar-collapse.collapse
          %form.navbar-form.navbar-right
            - if user_signed_in?
              %a.button#btnLogout.btn.btn-primary{:href => destroy_user_session_path, "data-method" => :delete, "aria-pressed" => "false", :autocomplete => "off", "data-toggle" => "button", :type => "button"} Log Out
        / /.navbar-collapse
    %p.notice= notice
    %p.alert= alert
    = yield   
%footer
  %p © Scott Pappas and Justin Beard 2014

app/views/rooms/_form.html.haml
= form_for(@room) do |f|
  - if @room.errors.any?
    #error_explanation
      %h2
        = pluralize(@room.errors.count, "error")
        prohibited this room from being saved:
      %ul
        - @room.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label 'Room Number'
    %br/
    = f.text_field :roomnumber
  .field
    = f.label 'Room Type'
    %br/
    = f.text_field :roomtype
  .field
    = f.label 'Room Description'
    %br/
    = f.text_area :roomdescription
  .field
    = f.label 'Room Price'
    %br/
    = f.text_field :roomprice
  .field
    = f.label 'Hotel Name'
    %br/
    = f.text_field :hotelname     
  .actions
    = f.submit

app/views/rooms/_form_new.html.haml
= form_for(@room) do |f|
  - if @room.errors.any?
    #error_explanation
      %h2
        = pluralize(@room.errors.count, "error")
        prohibited this room from being saved:
      %ul
        - @room.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label 'Room Number'
    %br/
    = f.text_field :roomnumber
  .field
    = f.label 'Room Type'
    %br/
    = f.text_field :roomtype
  .field
    = f.label 'Room Description'
    %br/
    = f.text_area :roomdescription
  .field
    = f.label 'Room Price'
    %br/
    = f.text_field :roomprice
  .field
    = f.text_field :hotel_id, :type => "hidden", :value => "#{@hotel.id}"          
  .field
    = f.text_field :hotelname, :type => "hidden" ,:value => "#{@hotel.hotelname}" 
  .actions
    = f.submit

app/views/rooms/edit.html.haml
%banner2 Edit Room Information

= render 'form'

= link_to 'Show', @room
|
= link_to 'Back', rooms_path
|
= link_to 'Home Page', root_path

app/views/rooms/index.html.haml
%banner2
  Listing of Rooms
%p#notice= notice
%table.table.table-bordered.table-striped.table-hover
  %thead
    %tr
      %th Hotel Name
      %th Room Number
      %th Room Type
      %th Room Description
      %th Room Price
      %th Select Option
  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.hotelname
        %td= room.roomnumber
        %td= room.roomtype
        %td= room.roomdescription
        %td= room.roomprice
        %td
          .dropdown
            %a#dLabel{"aria-expanded" => "false", "aria-haspopup" => "true", "data-target" => "#", "data-toggle" => "dropdown", :href => "http://example.com"}
              Action
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dLabel", :role => "menu"}
              %li= link_to 'Show', room
              %li= link_to 'Edit', edit_room_path(room)
              %li= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'Add Room', hotels_path
|
= link_to 'Home Page', root_path

app/views/rooms/new.html.haml
%p#notice= notice
%banner2
  Add A New Room #{@hotel.hotelname}
  
= render 'form_new'

= link_to 'Back', hotels_path
|
= link_to 'Home Page', root_path

app/views/rooms/show.html.haml
%p#notice= notice
%p
  %strong Room Number:
  = @room.roomnumber
%p
  %strong Room Type:
  = @room.roomtype
%p
  %strong Room Description:
  = @room.roomdescription
%p
  %strong Room Price: $
  = @room.roomprice
%p
  %strong Hotel Name:
  = @room.hotelname
  
= link_to 'Edit', edit_room_path(@room)
|
= link_to 'Back', rooms_path
|
= link_to 'Home Page', root_path

app/views/welcome/index.html.haml
/ Main jumbotron for a primary marketing message or call to action
.jumbotron
  .container
    %h1 Welcome to our Project
    %p For this project we have chosen to create an application that allows you to view, edit, create and remove hotels and the rooms within.
    %p
      %button.btn.btn-primary.btn-lg{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
        Learn More About Our Project
    / Modal
    #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
              %span.sr-only Close
            %h4#myModalLabel.modal-title Group 6 Authors and Information
          .modal-body
            %ul
              %li Scott Pappas
              %li Justin Beard
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
.container
  / Example row of columns
  .row
    .col-md-6
      %h2 View Hotels
      %p A list of all the hotels in our database
      %p
        %a.btn.btn-default{:href => hotels_path, :role => "button"} View Hotel List»
    .col-md-6
      %h2 View Rooms
      %p A list of all the rooms in our database
      %p
        %a.btn.btn-default{:href => rooms_path, :role => "button"} View Room List »
  %hr/
/ /container